name: "OpenJDK11U-jdk_x64_mac_hotspot_$(Year:yyyy)-$(Date:MM)-$(Date:dd)-$(Date:HH)-$(Date:mm)"

trigger: none
pr: none
schedules: []

variables:
  - group: codesign-certs

stages:
  - stage: Build
    jobs:
      - job: macOS
        pool:
          vmImage: "macOS-10.14"
        steps:
          - template: ./templates/build_steps.yml
            parameters:
              javaVersion: "jdk11u"

  - stage: Sign
    jobs:
      - job: macOS
        pool:
          vmImage: "macOS-10.14"
        steps:
          - template: ./templates/sign_steps.yml
