name: "OpenJDK11U-jdk_x64_mac_hotspot_$(Year:yyyy)-$(Date:MM)-$(Date:dd)-$(Date:HH)-$(Date:mm)"

trigger: none
pr: none
schedules: []

variables:
  - group: codesign-certs

stages:
  - stage: Build_and_Sign_macOS
    displayName: 'Build & Sign'
    jobs:

      - job: Build_macOS
        displayName: Build
        pool:
          vmImage: "macOS-10.14"
        steps:
          - template: ./templates/build_steps.yml
            parameters:
              javaVersion: "jdk11u"

      - job: Sign_macOS
        displayName: Sign
        dependsOn: Build_macOS
        pool:
          vmImage: "macOS-10.14"
        steps:
          - template: ./templates/sign_steps.yml

  - stage: Installer_macOS
    displayName: 'Installers'
    dependsOn: Build_and_Sign_macOS
    jobs:
      - job: Installer_macOS
        displayName: 'Installers'
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - template: ./templates/installer_steps.yml
            parameters:
              majorVersion: "11"
              fullVersion: "11+0.0.2" # TODO this needs to be worked out.


  - stage: Test_macOS
    displayName: 'Test'
    dependsOn: Build_and_Sign_macOS
    variables:
      ADOPT_TEST_REPO_URI: 'https://github.com/AdoptOpenJDK/openjdk-tests'
      ADOPT_TEST_REPO_BRANCH: 'master'
      ADOPT_JDK_SOURCE_URI: 'https://github.com/AdoptOpenJDK/openjdk-jdk11u'
      ADOPT_JDK_SOURCE_BRANCH: 'master'
    jobs:
    - template: ./tests/openjdk/sanity.yml
      parameters:
        pool:
          vmImage: macOS-10.14
    - template: ./tests/perf/sanity.yml
      parameters:
        pool:
          vmImage: macOS-10.14
    - template: ./tests/system/sanity.yml
      parameters:
        pool:
          vmImage: macOS-10.14

