name: "OpenJDK11U-jdk_x64_mac_hotspot_$(Year:yyyy)-$(Date:MM)-$(Date:dd)-$(Date:HH)-$(Date:mm)"

trigger: none
pr: none
schedules: []

variables:
  - group: codesign-certs

stages:
  - stage: Build_and_Sign_macOS
    displayName: 'Build & Sign'
    jobs:

      - job: Build_macOS
        displayName: Build
        pool:
          vmImage: "macOS-10.14"
        steps:
          - template: ./templates/build_steps.yml
            parameters:
              javaVersion: "jdk11u"

      - job: Sign_macOS
        displayName: Sign
        dependsOn: Build_macOS
        pool:
          vmImage: "macOS-10.14"
        steps:
          - template: ./templates/sign_steps.yml

  - stage: Test_macOS
    displayName: 'Test macOS'
    dependsOn: Build_and_Sign_macOS
    jobs:
      - job: Test_macOS
        displayName: 'Test'
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - script: |
              echo "Do the Tests here."
            displayName: 'Hello World'
