name: macOS

on:
  push:
    branches: [ master ]
  pull_request_target:
    types: [opened, synchronize, edited, reopened]
    branches: [ master ]
  issue_comment:
    types: [ created ]

jobs:
  check_if_run:
    name: Comment Checker
    runs-on: ubuntu-latest
    outputs:
      checker: ${{steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/build-macos'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  build_macos:
    needs: check_if_run
    if: needs.check_if_run.outputs.checker == 'true'
    name: build
    runs-on: macos-latest
    strategy:
      matrix:
        version: [jdk8u, jdk11u, jdk15u, jdk]
        vm: [hotspot, openj9]

    steps:
    - name: Github API Request
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout PR Branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
        ref: ${{ steps.pr_data.outputs.branch }}

    - name: Install Dependencies
      run: |
        brew install bash binutils freetype gnu-sed nasm

    - uses: actions/setup-java@v1
      id: setup-java
      with:
        java-version: 7
      if: matrix.version == 'jdk8u'
        
    - name: Build macOS
      run: |
        export JAVA_HOME=$JAVA_HOME_11_X64

        # Configure Xcode version explicitly. Default versions may change any time.
        # Available versions: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
        case "${{ matrix.version }}" in
          "jdk8u"|"jdk11u"|"jdk15u")
            export DEVELOPER_DIR="/Applications/Xcode_11.7.app/Contents/Developer"
            ;;
          "jdk")
            export DEVELOPER_DIR="/Applications/Xcode_12.1.app/Contents/Developer"
            ;;
          *)
            echo "Unknown JDK version: ${{ matrix.version }}" >&2
            exit 1
            ;;
        esac

        # Skip freetype build on jdk11+
        if [ ${{ matrix.version }} != "jdk8u" ]; then
          export BUILD_ARGS="--skip-freetype"
        fi
        ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: mac
        FILENAME: OpenJDK.tar.gz
        JDK7_BOOT_DIR: ${{ steps.setup-java.outputs.path }}
