name: Build

on:
  pull_request:
    types:
      - labeled

jobs:
  build_linux:
    name: Linux
    if: github.event.label.name == 'build-linux'
    runs-on: [ubuntu-latest]
    container:
      image: adoptopenjdk/centos7_build_image
    strategy:
      matrix:
        version: [jdk8u, jdk11u, jdk15u, jdk]
        vm: [hotspot, openj9]

    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check_linux
      with:
        trigger: 'build-linux'
        reaction: +1
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    - uses: actions/checkout@v2
      if: steps.check_linux.outputs.triggered == 'true'
        
    - name: Build Linux
      run: ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: linux
        FILENAME: OpenJDK.tar.gz
      if: steps.check_linux.outputs.triggered == 'true'

  build_macos:
    name: macOS
    if: github.event.label.name == 'build-mac'
    runs-on: [macos-latest]
    strategy:
      matrix:
        version: [jdk8u, jdk11u, jdk15u, jdk]
        vm: [hotspot, openj9]

    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check_macos
      with:
        trigger: 'build-macos'
        reaction: +1
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  
    - uses: actions/checkout@v2
      if: steps.check_macos.outputs.triggered == 'true'

    - name: Install Dependencies
      run: |
        brew install bash binutils freetype gnu-sed nasm
      if: steps.check_macos.outputs.triggered == 'true'

    - uses: actions/setup-java@v1
      id: setup-java
      with:
        java-version: 7
      if: matrix.version == 'jdk8u' && steps.check_macos.outputs.triggered == 'true'
        
    - name: Build macOS
      run: |
        export JAVA_HOME=$JAVA_HOME_11_X64
        # Skip freetype build on jdk11+
        if [ ${{ matrix.version }} != "jdk8u" ]; then
          export BUILD_ARGS="--skip-freetype"
        fi
        ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: mac
        FILENAME: OpenJDK.tar.gz
        JDK7_BOOT_DIR: ${{ steps.setup-java.outputs.path }}
      if: steps.check_macos.outputs.triggered == 'true'
