name: PR Status Bot

on:
  pull_request_target:
    types: [ ready_for_review ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment on PR'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            - [x] Checks complete
            - [x] Number of reviews required
